services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./backend:/app

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - postgres

  postgres:
    image: postgres:16

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: